spring.application.name=app-gateway
server.port=8080

# Eureka Client (Disabled for Static Routing)
eureka.client.enabled=false

# --- AUTH SERVICE (Localhost) ---
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**,/api/usuarios/**

# --- TASK SERVICE (Localhost) ---
spring.cloud.gateway.mvc.routes[1].id=task-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/tareas/**

# --- ACADEMIC SERVICE (Localhost) ---
spring.cloud.gateway.mvc.routes[2].id=academic-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/asignaturas/**,/api/evaluaciones/**

# JWT Validation (Must match auth_service secret)
jwt.secret=mi-clave-super-secreta-proyecto-final-123456789-idat-2026